import java.text.NumberFormat;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class RoundFloat {
    public float askForFloat() {
    	Scanner sc=new Scanner(System.in);
    	System.out.println("Input float number");
        return sc.nextFloat();
    }
    
    public int askForPrecision() {
    	Scanner sc=new Scanner(System.in);
    	System.out.println("Input what precision should be");
        return sc.nextInt();
    }
    
    public String roundFloat(float num, int precision) {
    	final NumberFormat numFormat = NumberFormat.getNumberInstance();
	    numFormat.setMaximumFractionDigits(precision);
	    return numFormat.format(num);
    }

    public static void main(String[] args) {
    	RoundFloat floatToRound= new RoundFloat();
        System.out.println("Rounded number : " + floatToRound.roundFloat(floatToRound.askForFloat(), floatToRound.askForPrecision()));
    }
}
