/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.io.ByteArrayInputStream;

public class RoundFloatTest {
    @Test public void appHasAFloat() {
        RoundFloat classUnderTest = new RoundFloat();
        assertNotNull(classUnderTest.askForFloat(), "app should have an input float");
    }
    
    @Test public void appHasAPrec() {
        RoundFloat classUnderTest = new RoundFloat();
        assertNotNull(classUnderTest.askForPrecision(), "app should have an input prec");
    }
    
    @Test public void appHasResult() {
        RoundFloat classUnderTest = new RoundFloat();
        assertEquals(classUnderTest.roundFloat(2.355f, 2), "2,36", "app should have an input prec");
    }
    
    @Test public void appReturnsProperValueAterInput() {
	    System.setIn(new ByteArrayInputStream("2,378".getBytes()));
	    RoundFloat classUnderTest = new RoundFloat();
		Float numGiven = classUnderTest.askForFloat();
		System.setIn(new ByteArrayInputStream("2".getBytes()));
		int precGiven = classUnderTest.askForPrecision();
		String roundedValue = classUnderTest.roundFloat(numGiven, precGiven);
		assertEquals(roundedValue, "2,38");
    }
}
